### ISSUE TITLE
Board doesn't update for shots

### ISSUE THREAD

**Issue by nagledb** [PSU-SW500-SU16-T5/sinking-feeling#105]
The shots function is currently adding each shot to the log of shots made, but the board isn't updating to reflect the outcome of the shot. We should probably remove the board from the database and regenerate it as needed using the shot log and ship position data.

**Comment by teeks99** [comment]
The shots function isn't getting called yet, that is waiting for #60 to hook it to the UI. I don't think this is a bug.

**Comment by nagledb** [comment]
I was a bit confused, part of what I thought needed to be done is already done and the rest is covered by #60
